"""create reward_ledger and user_points tables

Revision ID: 6aaea4dcc3d8
Revises: 6d5ba29aa2df
Create Date: 2026-07-04 14:06:30.785958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaea4dcc3d8'
down_revision: Union[str, None] = '6d5ba29aa2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_points',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reward_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_challenge_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.Enum('points', 'badge', name='reward_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('badge_code', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_challenge_id', name='uq_reward_user_challenge')
    )
    op.create_index(op.f('ix_reward_ledger_source_challenge_id'), 'reward_ledger', ['source_challenge_id'], unique=False)
    op.create_index(op.f('ix_reward_ledger_user_id'), 'reward_ledger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_ledger_user_id'), table_name='reward_ledger')
    op.drop_index(op.f('ix_reward_ledger_source_challenge_id'), table_name='reward_ledger')
    op.drop_table('reward_ledger')
    op.drop_table('user_points')
    # ### end Alembic commands ###
