"""create challenge_progress and user_daily_activity tables

Revision ID: 6d5ba29aa2df
Revises: 72566b6ab3b3
Create Date: 2026-07-04 13:23:37.467460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5ba29aa2df'
down_revision: Union[str, None] = '72566b6ab3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', 'activity_date', name='uq_activity_user_type_date')
    )
    op.create_index(op.f('ix_user_daily_activity_activity_date'), 'user_daily_activity', ['activity_date'], unique=False)
    op.create_index(op.f('ix_user_daily_activity_event_type'), 'user_daily_activity', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_daily_activity_user_id'), 'user_daily_activity', ['user_id'], unique=False)
    op.create_table('challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('in_progress', 'completed', name='progress_state'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', name='uq_progress_challenge_user')
    )
    op.create_index(op.f('ix_challenge_progress_challenge_id'), 'challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_progress_state'), 'challenge_progress', ['state'], unique=False)
    op.create_index(op.f('ix_challenge_progress_user_id'), 'challenge_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_progress_user_id'), table_name='challenge_progress')
    op.drop_index(op.f('ix_challenge_progress_state'), table_name='challenge_progress')
    op.drop_index(op.f('ix_challenge_progress_challenge_id'), table_name='challenge_progress')
    op.drop_table('challenge_progress')
    op.drop_index(op.f('ix_user_daily_activity_user_id'), table_name='user_daily_activity')
    op.drop_index(op.f('ix_user_daily_activity_event_type'), table_name='user_daily_activity')
    op.drop_index(op.f('ix_user_daily_activity_activity_date'), table_name='user_daily_activity')
    op.drop_table('user_daily_activity')
    # ### end Alembic commands ###
